# Generated by Django 4.1.4 on 2025-11-27 07:38

import apps.core.modelfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', apps.core.modelfields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', apps.core.modelfields.CreatedAtField(auto_now_add=True)),
                ('updated_at', apps.core.modelfields.UpdatedAtField(auto_now=True)),
                ('is_active', apps.core.modelfields.IsActiveField(default=True)),
                ('enabled_at', apps.core.modelfields.EnabledAtField(editable=False, null=True)),
                ('name', apps.core.modelfields.NameField(max_length=255)),
                ('slug', apps.core.modelfields.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('created_by', apps.core.modelfields.CreatedByField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='category.category')),
                ('updated_by', apps.core.modelfields.UpdatedByField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='category_ca_slug_6890c5_idx'),
        ),
    ]
