# Generated by Django 4.1.4 on 2025-11-27 15:47

import apps.core.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=apps.core.modelfields.NameField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=apps.core.modelfields.NameField(max_length=255, null=True),
        ),
    ]
