# Generated by Django 4.1.4 on 2025-11-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_name_ar_category_name_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
