# Generated by Django 4.1.4 on 2026-02-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['is_published', 'is_active'], name='program_pub_active_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['category', '-created_at'], name='program_cat_created_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['type', 'language'], name='program_type_lang_idx'),
        ),
    ]
