# Generated by Django 4.1.4 on 2025-11-28 05:52

import apps.core.modelfields
import apps.editor.modelfields
import apps.user.modelfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', apps.core.modelfields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', apps.core.modelfields.CreatedAtField(auto_now_add=True)),
                ('updated_at', apps.core.modelfields.UpdatedAtField(auto_now=True)),
                ('is_active', apps.core.modelfields.IsActiveField(default=True)),
                ('enabled_at', apps.core.modelfields.EnabledAtField(editable=False, null=True)),
                ('name', apps.core.modelfields.NameField(max_length=255)),
                ('name_en', apps.core.modelfields.NameField(max_length=255, null=True)),
                ('name_ar', apps.core.modelfields.NameField(max_length=255, null=True)),
                ('email', apps.core.modelfields.EmailField(max_length=254)),
                ('sort_order', apps.core.modelfields.SortOrderField(db_index=True, default=0)),
                ('description', apps.core.modelfields.DescriptionField(blank=True, null=True)),
                ('created_by', apps.core.modelfields.CreatedByField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', apps.core.modelfields.UpdatedByField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'editor',
                'verbose_name_plural': 'editors',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorUser',
            fields=[
                ('id', apps.core.modelfields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', apps.core.modelfields.CreatedAtField(auto_now_add=True)),
                ('updated_at', apps.core.modelfields.UpdatedAtField(auto_now=True)),
                ('is_manager', apps.editor.modelfields.IsManagerField(default=False)),
                ('editor', apps.editor.modelfields.EditorField(on_delete=django.db.models.deletion.CASCADE, related_name='editorusers', to='editor.editor')),
                ('user', apps.user.modelfields.UserOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'editor_user',
                'verbose_name_plural': 'editor_users',
                'ordering': ['-created_at'],
            },
        ),
    ]
