# Generated by Django 4.1.4 on 2026-01-26 22:01

import apps.core.modelfields
import apps.editor.modelfields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='phone_number',
            field=apps.core.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='editor',
            name='user',
            field=apps.editor.modelfields.UserField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EditorUser',
        ),
    ]
