# Generated by Django 4.1.4 on 2025-11-27 13:56

import apps.core.modelfields
import apps.user.modelfields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', apps.core.modelfields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', apps.core.modelfields.CreatedAtField(auto_now_add=True)),
                ('updated_at', apps.core.modelfields.UpdatedAtField(auto_now=True)),
                ('created_by', apps.core.modelfields.CreatedByField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', apps.core.modelfields.UpdatedByField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', apps.user.modelfields.UserOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
