# Generated by Django 4.1.4 on 2025-11-28 11:27

import apps.core.modelfields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_initial'),
        ('episode', '0003_episode_enabled_at_episode_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', apps.core.modelfields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', apps.core.modelfields.CreatedAtField(auto_now_add=True)),
                ('updated_at', apps.core.modelfields.UpdatedAtField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('system', models.CharField(choices=[('youtube', 'YouTube'), ('rss', 'RSS'), ('manual', 'Manual'), ('other', 'Other')], default='manual', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'content source',
                'verbose_name_plural': 'content sources',
            },
        ),
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', apps.core.modelfields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', apps.core.modelfields.CreatedAtField(auto_now_add=True)),
                ('updated_at', apps.core.modelfields.UpdatedAtField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('program', 'program'), ('episode', 'episode')], max_length=16)),
                ('external_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('success', 'success'), ('failed', 'failed')], default='success', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_records', to='episode.episode')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_records', to='program.program')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='importer.contentsource')),
            ],
            options={
                'verbose_name': 'importer record',
                'verbose_name_plural': 'importer records',
                'unique_together': {('source', 'entity_type', 'external_id')},
            },
        ),
    ]
