# Generated by Django 4.1.4 on 2025-11-27 18:06

import apps.core.modelfields
import apps.program.modelfields
import apps.tag.modelfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0003_remove_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', apps.core.modelfields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', apps.core.modelfields.CreatedAtField(auto_now_add=True)),
                ('updated_at', apps.core.modelfields.UpdatedAtField(auto_now=True)),
                ('is_active', apps.core.modelfields.IsActiveField(default=True)),
                ('enabled_at', apps.core.modelfields.EnabledAtField(editable=False, null=True)),
                ('title', apps.program.modelfields.TitleField(max_length=255)),
                ('slug', apps.core.modelfields.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('short_description', apps.program.modelfields.ShortDescriptionField(blank=True, max_length=500, null=True)),
                ('long_description', apps.program.modelfields.LongDescriptionField(blank=True, null=True)),
                ('type', apps.program.modelfields.ProgramTypeField(choices=[('podcast', 'Podcast'), ('documentary', 'Documentary'), ('show', 'Show'), ('other', 'Other')], default='podcast', max_length=50)),
                ('language', apps.program.modelfields.LanguageField(choices=[('en', 'English'), ('ar', 'العربية')], default='en', max_length=10)),
                ('cover_image_url', apps.core.modelfields.UrlField(blank=True, max_length=1000, null=True)),
                ('accent_color', apps.program.modelfields.ColorField(blank=True, max_length=20, null=True)),
                ('publish_date', apps.program.modelfields.PublishDateField(blank=True, null=True)),
                ('is_published', apps.program.modelfields.IsPublishedField(default=False)),
                ('is_featured', apps.program.modelfields.IsFeaturedField(default=False)),
                ('episodes_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='category.category')),
                ('created_by', apps.core.modelfields.CreatedByField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('tags', apps.tag.modelfields.TagsField(blank=True, related_name='%(class)ss', to='tag.tag')),
                ('updated_by', apps.core.modelfields.UpdatedByField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'program',
                'verbose_name_plural': 'programs',
                'ordering': ['-created_at'],
            },
        ),
    ]
