# Generated by Django 4.1.4 on 2025-11-27 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
    ]
