import random
import string

from django.utils.functional import keep_lazy_text
from django.utils.text import slugify as django_slugify


def random_string(size=6, chars=string.ascii_lowercase + string.digits):
    """
    This function returns random symbols generated by it.
    """
    return ''.join(random.choice(chars) for _ in range(size))


@keep_lazy_text
def slugify(instance, field_name=None, new_slug=None):
    """
    This function returns a unique identifier by searching for this identifier within the model.
    If it exists, another one is generated and then verified. If it does not exist, it is returned.
    """
    klass = instance.__class__
    new_slug = new_slug if new_slug else getattr(instance, field_name, 'unknown')
    slug = django_slugify(new_slug, allow_unicode=True)

    if not klass.objects.filter(slug=slug).exists():
        return slug

    new_slug = f"{slug}-{random_string()}"
    return slugify(instance, new_slug=new_slug)