# Generated by Django 4.1.4 on 2025-11-27 18:06

import apps.core.modelfields
import apps.episode.modelfields
import apps.program.modelfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', apps.core.modelfields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', apps.core.modelfields.CreatedAtField(auto_now_add=True)),
                ('updated_at', apps.core.modelfields.UpdatedAtField(auto_now=True)),
                ('title', apps.episode.modelfields.TitleField(max_length=255)),
                ('slug', apps.core.modelfields.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('short_description', apps.program.modelfields.ShortDescriptionField(blank=True, max_length=500, null=True)),
                ('body', apps.core.modelfields.DescriptionField(blank=True, null=True)),
                ('publish_date', apps.episode.modelfields.PublishDateTimeField(blank=True, null=True)),
                ('duration_seconds', apps.episode.modelfields.DurationSecondsField()),
                ('episode_number', apps.episode.modelfields.EpisodeNumberField()),
                ('season_number', apps.episode.modelfields.SeasonNumberField(blank=True, null=True)),
                ('thumbnail_url', apps.program.modelfields.UrlField(blank=True, null=True)),
                ('media_type', apps.episode.modelfields.MediaTypeField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=20)),
                ('media_url', apps.core.modelfields.UrlField(blank=True, max_length=1000, null=True)),
                ('is_published', apps.episode.modelfields.IsPublishedField(default=False)),
                ('is_featured', apps.episode.modelfields.IsFeaturedField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.CharField(blank=True, max_length=512)),
                ('created_by', apps.core.modelfields.CreatedByField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'episode',
                'verbose_name_plural': 'episodes',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='EpisodeLink',
            fields=[
                ('id', apps.core.modelfields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', apps.core.modelfields.CreatedAtField(auto_now_add=True)),
                ('updated_at', apps.core.modelfields.UpdatedAtField(auto_now=True)),
                ('label', apps.episode.modelfields.TitleField(max_length=255)),
                ('url', apps.program.modelfields.UrlField(blank=True, null=True)),
                ('sort_order', apps.core.modelfields.SortOrderField(db_index=True, default=0)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='episode.episode')),
            ],
            options={
                'verbose_name': 'episode link',
                'verbose_name_plural': 'episode links',
                'ordering': ['sort_order'],
            },
        ),
    ]
