# Generated by Django 4.1.4 on 2025-11-27 18:06

import apps.core.modelfields
import apps.episode.modelfields
import apps.tag.modelfields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        ('episode', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='program',
            field=apps.episode.modelfields.ProgramField(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='program.program'),
        ),
        migrations.AddField(
            model_name='episode',
            name='tags',
            field=apps.tag.modelfields.TagsField(blank=True, related_name='%(class)ss', to='tag.tag'),
        ),
        migrations.AddField(
            model_name='episode',
            name='updated_by',
            field=apps.core.modelfields.UpdatedByField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
