# Generated by Django 4.1.4 on 2025-11-27 22:49

import apps.core.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='enabled_at',
            field=apps.core.modelfields.EnabledAtField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='is_active',
            field=apps.core.modelfields.IsActiveField(default=True),
        ),
    ]
