# Generated by Django 4.1.4 on 2026-02-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0003_episode_enabled_at_episode_is_active'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['is_published', 'is_active'], name='episode_pub_active_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['program', '-publish_date'], name='episode_program_pub_date_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['media_type'], name='episode_media_type_idx'),
        ),
    ]
