import math

from django.core.paginator import Page, Paginator, InvalidPage

from rest_framework.exceptions import NotFound
from rest_framework.pagination import PageNumberPagination
from rest_framework.response import Response
from rest_framework.utils.urls import replace_query_param


def positive_int(integer_string, strict=False, cutoff=None):
    ret = int(integer_string)
    if ret == 0 and strict:
        raise ValueError()
    if cutoff:
        return min(ret, cutoff)
    return ret


class Page(Page):

    def next_page_number(self):
        return self.number * self.paginator.per_page

    def previous_page_number(self):
        return ((self.number - 1) * self.paginator.per_page) - self.paginator.per_page


class Paginator(Paginator):
    """
    Translators: String used to replace omitted page numbers in elided page
    range generated by paginators, e.g. [1, 2, '…', 5, 6, 7, '…', 9, 10].
    """

    def _get_page(self, *args, **kwargs):
        """
        Return an instance of a single page.

        This hook can be used by subclasses to use an alternative to the
        standard :cls:`Page` object.
        """
        return Page(*args, **kwargs)


class Pagination(PageNumberPagination):
    """
    A simple page number based style that supports page numbers as
    query parameters. For example:
    """

    # The default page size.
    # Defaults to `None`, meaning pagination is disabled.
    page_size = 10

    django_paginator_class = Paginator

    # Client can control the page using this query parameter.
    page_query_param = 'start'

    # Client can control the page size using this query parameter.
    page_size_query_param = 'length'

    # Set to an integer to limit the maximum page size the client may request.
    # Only relevant if 'page_size_query_param' has also been set.
    max_page_size = 100

    def __init__(self, *args, **kwargs):
        """
        When you create a new object of a class, Python automatically calls the __init__() method to
        initialize the object’s attributes.
        """

        self.page = None
        self.request = None
        super(Pagination, self).__init__(*args, **kwargs)

    def get_page_number(self, request, paginator, page_size):
        """
        This method returns the page number through a mathematical equation to calculate
        the beginning of the query along with the length of the query
        """

        page_number = request.query_params.get(self.page_query_param, 0)

        if page_number in self.last_page_strings:
            page_number = paginator.num_pages

        if int(page_number) < page_size:
            return 1

        return abs(math.ceil((int(page_number) / page_size))) + 1

    def paginate_queryset(self, queryset, request, view=None):
        """
        Paginate a queryset if required, either returning a
        page object, or `None` if pagination is not configured for this view.
        """

        page_size = self.get_page_size(request)

        if not page_size:
            return None

        if page_size < 0:
            page_size = queryset.count() or 10

        paginator = self.django_paginator_class(queryset, page_size)
        page_number = self.get_page_number(request, paginator, page_size)

        try:
            self.page = paginator.page(page_number)
        except InvalidPage as exc:
            msg = self.invalid_page_message.format(page_number=page_number, message=str(exc))
            raise NotFound(msg)

        if paginator.num_pages > 1 and self.template is not None:
            # The browsable API should display pagination controls.
            self.display_page_controls = True

        self.request = request
        return list(self.page)

    def get_page_size(self, request):
        """
        This method returns the number of pages
        """

        if self.page_size_query_param:
            try:
                return positive_int(
                    request.query_params[self.page_size_query_param],
                    strict=True,
                    cutoff=self.max_page_size
                )
            except (KeyError, ValueError):
                pass

        return self.page_size

    def get_previous_link(self):
        if not self.page.has_previous():
            return None
        url = self.request.build_absolute_uri()
        page_number = self.page.previous_page_number()
        return replace_query_param(url, self.page_query_param, page_number)

    def get_paginated_response(self, data):
        return Response(
            {
                "page": self.page.number,
                "num_pages": self.page.paginator.num_pages,
                "recordsTotal": self.page.paginator.count,
                "recordsFiltered": self.page.paginator.count,
                'next_url': self.get_next_link(),
                'previous': self.get_previous_link(),
                "data": data,
            }
        )
