# Generated by Django 4.1.4 on 2023-10-30 15:39

import apps.core.modelfields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', apps.core.modelfields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', apps.core.modelfields.CreatedAtField(auto_now_add=True)),
                ('updated_at', apps.core.modelfields.UpdatedAtField(auto_now=True)),
                ('is_active', apps.core.modelfields.IsActiveField(default=True)),
                ('enabled_at', apps.core.modelfields.EnabledAtField(editable=False, null=True)),
                ('name', apps.core.modelfields.NameField(max_length=255)),
                ('name_en', apps.core.modelfields.NameField(max_length=255, null=True)),
                ('name_ar', apps.core.modelfields.NameField(max_length=255, null=True)),
                ('note', apps.core.modelfields.NoteField(blank=True, null=True)),
                ('created_by', apps.core.modelfields.CreatedByField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', apps.core.modelfields.UpdatedByField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['-id'],
            },
        ),
    ]
